# The REDIS_PASSWORD must be set with for example
# export REDIS_PASSWORD=AStrongPassw0rd
# docker-compose up
version: "3.3"
services:

 redis:
    image: redis
    command: redis-server --requirepass "$REDIS_PASSWORD"
    hostname: "redis"
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

 keystore:
    build: rest-server
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "$REDIS_PASSWORD"
    ports:
     - "80:5000"

